export const Endpoint = Object.freeze({
    ADDRESS: '/n/v1/address/',
    API_CLIENT: '/n/v1/apiclient/',
    BEARER_TOKEN: '/n/v1/bearertoken/',
    BOOLEAN: '/n/v1/booleanitem/',
    BOOLEAN_HISTORY : '/n/v1/booleanitemhistory/',
    CLIENT_CONTEXT : '/n/v1/clientcontext',
    CLIENT_IDENTIFIER: '/n/v1/clientidentifier/',
    COMPANIES: '/n/v1/companies',
    COMPANY: '/n/v1/company/',
    DATE_TIME: '/n/v1/datetimeitem/',
    DATE_TIME_HISTORY: '/n/v1/datetimeitemhistory/',
    DOUBLE: '/n/v1/doubleitem/',
    DOUBLE_HISTORY: '/n/v1/doubleitemhistory/',
    EMAIL: '/n/v1/email/',
    ENTITY: '/n/v1/entity/',
    ENTITY_LIST: '/n/v1/entitylist/',
    ENTITY_VIEW : '/v/v1/entityview/',
    GROUP: '/n/v1/group/',
    GROUP_MEMBERSHIP: '/n/v1/groupmembership/',
    IDENTITY: '/n/v1/identity/',
    IDENTITY_NOTIFICATION_INBOX: '/n/v1/identitynotificationinbox/',
    IMAGE: '/n/v1/imageitem/',
    IMAGE_HISTORY: '/n/v1/imageitemhistory/',
    IMAGE_FILE: '/n/v1/imageitemfile',
    JSON: '/n/v1/jsonitem/',
    JSON_HISTORY: '/n/v1/jsonitemhistory/',
    LAT_LONG: '/n/v1/latlongitem/',
    LAT_LONG_HISTORY: '/n/v1/latlongitemhistory/',
    LINK: '/n/v1/linkitem/',
    LINK_HISTORY: '/n/v1/linkitemhistory/',
    LONG: '/n/v1/longitem/',
    LONG_HISTORY: '/n/v1/longitemhistory/',
    MARKDOWN:  '/n/v1/markdownitem/',
    MARKDOWN_HISTORY: '/n/v1/markdownitemhistory/',
    MESSAGE_THREAD: '/n/v1/messagethread/',
    MESSAGE_THREAD_NOTIFICATION: '/n/v1/messagethreadnotificaiton/',
    MONEY: '/n/v1/moneyitem/',
    MONEY_HISTORY: '/n/v1/moneyitemhistory/',
    OAUTH_TOKEN: '/n/v1/oauthtoken/',
    PAYMENT_INVOICE: '/n/v1/paymentinvoice/',
    PERMISSION: '/n/v1/permission/',
    PERSON: '/n/v1/person/',
    PERSON_NAME: '/n/v1/personname/',
    SEARCH : '/n/v1/search/',
    REFERENCE: '/n/v1/referenceitem/',
    /** Not yet released; follows the pattern of the other item history endpoints. */
    REFERENCE_HISTORY: '/n/v1/referenceitemhistory/',
    TASK: '/n/v1/task/',
    TASK_LOG: '/n/v1/tasklog/',
    TASK_LOGS: '/n/v1/tasklogs/',
    TEMPLATE: '/n/v1/templateitem/',
    TEMPLATE_HISTORY: '/n/v1/templateitemhistory/',
    TEXT: '/n/v1/textitem/',
    TEXT_HISTORY: '/n/v1/textitemhistory/',
    THREAD_POST: '/n/v1/threadpost/',
    WEBHOOK_SUBSCRIPTION: '/n/v1/webhooksubscription/',
    WEBHOOK_TRIGGER: '/n/v1/webhooktrigger/',
    WORKFLOW: '/n/v1/workflow/'
});



